package com.mycompany.proyectovacunaslemus;

import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.stream.Collectors;

public class FrmBinarioPrincipal extends javax.swing.JFrame {

    private DefaultTableModel originalTableModel;

    /**
     * Creates new form FrmBinarioPrincipal
     */
    public FrmBinarioPrincipal() {
        initComponents();
        originalTableModel = (DefaultTableModel) tblBinario.getModel();
        PanelBusqueda.setVisible(false);
        setLocationRelativeTo(null);

    }

// Método para mostrar los datos en la tabla tblBinario
    public void mostrarDatosEnTabla(List<Object[]> data) {
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos

        for (Object[] row : data) {
            model.addRow(row);
        }
    }
    // Método para contar y mostrar la cantidad de registros en la tabla

    public void contarYMostrarCantidadRegistros() {
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        int rowCount = model.getRowCount();
        txtContador.setText(String.valueOf(rowCount));
    }

    public void setTiempoTranscurrido(long elapsedTime) {
        txtTiempo.setText(String.valueOf(elapsedTime) + " ms");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPreOrden = new javax.swing.JButton();
        btnPostOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBinario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContador = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        btnBorrarCargar = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        AccionesBusquedaInsercion = new javax.swing.JButton();
        PanelBusqueda = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDpi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtFechaPrimera = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaSegunda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFechaTercera = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLugarVacunacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizarDatos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEncriptar = new javax.swing.JButton();
        btnDesencriptar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardarTabla = new javax.swing.JButton();
        btnGenerarArbol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Arbol Binario");

        btnPreOrden.setText("Pre-Orden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });

        btnPostOrden.setText("Post-Orden");
        btnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrdenActionPerformed(evt);
            }
        });

        btnInOrden.setText("In-Orden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tblBinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Dpi", "Departamento ", "Municipio", "Primera Fecha", "Segunda Fecha", "Tercera Fecha", "Lugar de Vacunacion"
            }
        ));
        tblBinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBinarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBinario);

        jLabel2.setText("Persona Contabilizadas:");

        jLabel3.setText("Tiempo de busqueda");

        btnBorrarCargar.setText("Buscar otra tabla");
        btnBorrarCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCargarActionPerformed(evt);
            }
        });

        btnRestablecer.setText("Restablecer tabla");
        btnRestablecer.setEnabled(false);
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        AccionesBusquedaInsercion.setText("Hacer Insercion o Busqueda");
        AccionesBusquedaInsercion.setEnabled(false);
        AccionesBusquedaInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionesBusquedaInsercionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPreOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnPostOrden)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestablecer)
                        .addGap(18, 18, 18)
                        .addComponent(AccionesBusquedaInsercion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addGap(74, 74, 74))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreOrden)
                    .addComponent(btnPostOrden)
                    .addComponent(btnInOrden)
                    .addComponent(btnBorrarCargar)
                    .addComponent(btnRestablecer)
                    .addComponent(AccionesBusquedaInsercion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        PanelBusqueda.setBackground(new java.awt.Color(204, 255, 204));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DPI:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Departamento");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Municipio");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Primera Fecha:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Segunda Fecha");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Tercera Fecha");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Lugar de Vacunacion");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizarDatos.setText("Actualizar");
        btnActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEncriptar.setText("Encriptar Archivo");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        btnDesencriptar.setText("Desencriptar");
        btnDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencriptarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardarTabla.setText("Guardar Tabla");
        btnGuardarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTablaActionPerformed(evt);
            }
        });

        btnGenerarArbol.setText("Mostrar Arbol");
        btnGenerarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBusquedaLayout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelBusquedaLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(btnBuscar))
                        .addGroup(PanelBusquedaLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaTercera, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtLugarVacunacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarDatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                .addComponent(btnEncriptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesencriptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarTabla)))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerarArbol)
                .addGap(23, 23, 23))
            .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBusquedaLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(txtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaTercera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtLugarVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnGenerarArbol)
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizarDatos)
                    .addComponent(jButton2)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncriptar)
                    .addComponent(btnDesencriptar)
                    .addComponent(btnGuardarTabla))
                .addGap(19, 19, 19))
            .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBusquedaLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(txtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void recorrerArbol(String tipoRecorrido) {
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        BinaryTree binaryTree = new BinaryTree();

        for (int i = 0; i < model.getRowCount(); i++) {
            String name = (String) model.getValueAt(i, 0);
            String dpi = (String) model.getValueAt(i, 1);
            String departamento = (String) model.getValueAt(i, 2);
            String municipio = (String) model.getValueAt(i, 3);
            String fechaPrimera = (String) model.getValueAt(i, 4);
            String fechaSegunda = (String) model.getValueAt(i, 5);
            String fechaTercera = (String) model.getValueAt(i, 6);
            String lugarVacunacion = (String) model.getValueAt(i, 7);
            binaryTree.insert(name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
        }

        model.setRowCount(0); // Limpiar la tabla

        switch (tipoRecorrido) {
            case "preorden":
                binaryTree.preorden(binaryTree.getRoot(), model);
                break;
            case "inorden":
                binaryTree.inorden(binaryTree.getRoot(), model);
                break;
            case "postorden":
                binaryTree.postorden(binaryTree.getRoot(), model);
                break;
        }

        btnRestablecer.setEnabled(true);
        AccionesBusquedaInsercion.setEnabled(true);
    }

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed

        recorrerArbol("preorden");

        btnRestablecer.setEnabled(true);
        AccionesBusquedaInsercion.setEnabled(true);

    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void btnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrdenActionPerformed
        recorrerArbol("postorden");

        /*btnInOrden.setEnabled(false);
        btnPreOrden.setEnabled(false);*/
        btnRestablecer.setEnabled(true);
        AccionesBusquedaInsercion.setEnabled(true);

    }//GEN-LAST:event_btnPostOrdenActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        recorrerArbol("inorden");

        /*  btnPreOrden.setEnabled(false);
        btnPostOrden.setEnabled(false);*/
        btnRestablecer.setEnabled(true);
        AccionesBusquedaInsercion.setEnabled(true);

    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void cargarDatosDesdeArchivo(File file, int numRecords) {
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos

        int recordsLoaded = 0; // Contador para llevar la cuenta de registros cargados

        // Capturar el tiempo de inicio
        long startTime = System.currentTimeMillis();

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"))) {
            String line;
            while ((line = reader.readLine()) != null && recordsLoaded < numRecords) {
                String[] parts = line.split("\t");
                if (parts.length >= 2) {
                    String name = parts[0];
                    String dpi = parts[1];
                    model.addRow(new Object[]{name, dpi});
                    recordsLoaded++; // Incrementar el contador de registros cargados
                }
            }

            // Contar y mostrar la cantidad de registros cargados
            countAndDisplayRecords();

            // Capturar el tiempo de finalización y calcular el tiempo transcurrido
            long endTime = System.currentTimeMillis();
            long elapsedTime = endTime - startTime;

            // Mostrar el tiempo transcurrido en el campo txtTiempo
            txtTiempo.setText(String.valueOf(elapsedTime) + " ms");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void countAndDisplayRecords() {
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        int rowCount = model.getRowCount();
        txtContador.setText(String.valueOf(rowCount));
    }
    private void btnBorrarCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCargarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (.txt)", "txt"));

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // Mostrar ventana emergente para ingresar la cantidad de registros a cargar
            String input = JOptionPane.showInputDialog(this, "Ingrese la cantidad de registros a cargar:");
            if (input != null && !input.isEmpty()) {
                try {
                    int numRecords = Integer.parseInt(input);
                    if (numRecords <= 0) {
                        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número mayor que cero.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Cargar datos desde el archivo y mostrarlos en la tabla
                    cargarDatosDesdeArchivo(selectedFile, numRecords);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        btnInOrden.setEnabled(true);
        btnPostOrden.setEnabled(true);
        btnPreOrden.setEnabled(true);
    }//GEN-LAST:event_btnBorrarCargarActionPerformed

    private void restaurarTablaOriginal() {
        tblBinario.setModel(originalTableModel);
        countAndDisplayRecords(); // Actualizar el contador de registros
    }


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String searchText = txtBusqueda.getText().trim().toLowerCase();

        if (searchText.isEmpty()) {
            // Mostrar mensaje de advertencia si el campo de búsqueda está vacío
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un término de búsqueda.", "Búsqueda Vacía", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        boolean encontrado = false;

        // Crear un nuevo modelo para almacenar los resultados de la búsqueda
        DefaultTableModel searchResultsModel = new DefaultTableModel();
        searchResultsModel.setColumnIdentifiers(new String[]{"Nombres", "DPI", "Departamento", "Municipio", "Primera Fecha", "Segunda Fecha", "Tercera Fecha", "Lugar de Vacunacion"});

        // Recorrer la tabla para buscar coincidencias
        for (int i = 0; i < model.getRowCount(); i++) {
            String nombre = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString().toLowerCase() : "";
            String dpi = model.getValueAt(i, 1) != null ? model.getValueAt(i, 1).toString().toLowerCase() : "";
            String departamento = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString().toLowerCase() : "";
            String municipio = model.getValueAt(i, 3) != null ? model.getValueAt(i, 3).toString().toLowerCase() : "";
            String fechaPrimera = model.getValueAt(i, 4) != null ? model.getValueAt(i, 4).toString().toLowerCase() : "";
            String fechaSegunda = model.getValueAt(i, 5) != null ? model.getValueAt(i, 5).toString().toLowerCase() : "";
            String fechaTercera = model.getValueAt(i, 6) != null ? model.getValueAt(i, 6).toString().toLowerCase() : "";
            String lugarVacunacion = model.getValueAt(i, 7) != null ? model.getValueAt(i, 7).toString().toLowerCase() : "";

            // Verificar si algún campo contiene el texto de búsqueda
            if (nombre.contains(searchText) || dpi.contains(searchText) || departamento.contains(searchText)
                    || municipio.contains(searchText) || fechaPrimera.contains(searchText) || fechaSegunda.contains(searchText)
                    || fechaTercera.contains(searchText) || lugarVacunacion.contains(searchText)) {

                // Agregar la fila que coincide con la búsqueda al nuevo modelo de resultados
                searchResultsModel.addRow(new Object[]{
                    model.getValueAt(i, 0), model.getValueAt(i, 1), model.getValueAt(i, 2),
                    model.getValueAt(i, 3), model.getValueAt(i, 4), model.getValueAt(i, 5),
                    model.getValueAt(i, 6), model.getValueAt(i, 7)
                });
                encontrado = true;
            }
        }

        if (encontrado) {
            // Limpiar la tabla y mostrar los resultados de la búsqueda
            tblBinario.setModel(searchResultsModel);
            contarYMostrarCantidadRegistros(); // Actualizar el contador de registros
        } else {
            // Mostrar mensaje de que no se encontraron resultados
            JOptionPane.showMessageDialog(this, "No se encontraron registros que coincidan con el término de búsqueda.", "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
        }

        // Limpiar el campo de búsqueda después de realizar la búsqueda
        txtBusqueda.setText("");

        // Limpiar el campo de búsqueda después de realizar la búsqueda
        txtBusqueda.setText("");
        btnBorrarCargar.setEnabled(false);
        /* btnBuscar.setEnabled(false);
        btnInOrden.setEnabled(false);
        btnPostOrden.setEnabled(false);
    
        btnPreOrden.setEnabled(false);*/
        btnRegresar.setEnabled(false);
        LimpiarTextField();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        // Llamar al método para restaurar la tabla original
        restaurarTablaOriginal();
        JOptionPane.showMessageDialog(this, "Tabla restaurada a su estado original.", "Restauración Exitosa", JOptionPane.INFORMATION_MESSAGE);
        btnBorrarCargar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnRegresar.setEnabled(true);


    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void AccionesBusquedaInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionesBusquedaInsercionActionPerformed
        PanelBusqueda.setVisible(true);
        AccionesBusquedaInsercion.setVisible(false);
    }//GEN-LAST:event_AccionesBusquedaInsercionActionPerformed
    private int selectedRowIndex = -1;

    private void tblBinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBinarioMouseClicked
        // Obtener el índice de la fila seleccionada
        selectedRowIndex = tblBinario.getSelectedRow();

        // Verificar si se hizo clic con el botón izquierdo del ratón y si hay una fila seleccionada
        if (evt.getButton() == MouseEvent.BUTTON1 && selectedRowIndex != -1) {
            // Obtener el modelo de la tabla
            DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();

            // Obtener los datos de la fila seleccionada
            String nombre = (String) model.getValueAt(selectedRowIndex, 0);
            String dpi = (String) model.getValueAt(selectedRowIndex, 1);
            String departamento = (String) model.getValueAt(selectedRowIndex, 2);
            String municipio = (String) model.getValueAt(selectedRowIndex, 3);
            String fechaPrimera = (String) model.getValueAt(selectedRowIndex, 4);
            String fechaSegunda = (String) model.getValueAt(selectedRowIndex, 5);
            String fechaTercera = (String) model.getValueAt(selectedRowIndex, 6);
            String lugarVacunacion = (String) model.getValueAt(selectedRowIndex, 7);

            // Mostrar los datos en los JTextField correspondientes
            txtNombre.setText(nombre);
            txtDpi.setText(dpi);
            txtDepartamento.setText(departamento);
            txtMunicipio.setText(municipio);
            txtFechaPrimera.setText(fechaPrimera);
            txtFechaSegunda.setText(fechaSegunda);
            txtFechaTercera.setText(fechaTercera);
            txtLugarVacunacion.setText(lugarVacunacion);
        }
    }//GEN-LAST:event_tblBinarioMouseClicked

    private void btnActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosActionPerformed
        // Verificar si hay una fila seleccionada
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener datos de los JTextField
        String nombre = txtNombre.getText().trim();
        String dpi = txtDpi.getText().trim();
        String departamento = txtDepartamento.getText().trim();
        String municipio = txtMunicipio.getText().trim();
        String fechaPrimera = txtFechaPrimera.getText().trim();
        String fechaSegunda = txtFechaSegunda.getText().trim();
        String fechaTercera = txtFechaTercera.getText().trim();
        String lugarVacunacion = txtLugarVacunacion.getText().trim();

        // Validar que al menos el nombre y el DPI estén presentes
        if (nombre.isEmpty() || dpi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre y el DPI son campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();

        // Actualizar la fila seleccionada con los nuevos datos
        model.setValueAt(nombre, selectedRowIndex, 0);
        model.setValueAt(dpi, selectedRowIndex, 1);
        model.setValueAt(departamento, selectedRowIndex, 2);
        model.setValueAt(municipio, selectedRowIndex, 3);
        model.setValueAt(fechaPrimera, selectedRowIndex, 4);
        model.setValueAt(fechaSegunda, selectedRowIndex, 5);
        model.setValueAt(fechaTercera, selectedRowIndex, 6);
        model.setValueAt(lugarVacunacion, selectedRowIndex, 7);

        // Limpiar los JTextField
        LimpiarTextField();

        // Reiniciar el índice de la fila seleccionada
        selectedRowIndex = -1;

        // Actualizar el contador de registros
        countAndDisplayRecords();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Registro actualizado exitosamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);

        // Guardar la tabla actualizada como la original
        originalTableModel = (DefaultTableModel) tblBinario.getModel();
    }//GEN-LAST:event_btnActualizarDatosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // Obtener datos de los JTextField
        String nombre = txtNombre.getText().trim();
        String dpi = txtDpi.getText().trim();
        String departamento = txtDepartamento.getText().trim();
        String municipio = txtMunicipio.getText().trim();
        String fechaPrimera = txtFechaPrimera.getText().trim();
        String fechaSegunda = txtFechaSegunda.getText().trim();
        String fechaTercera = txtFechaTercera.getText().trim();
        String lugarVacunacion = txtLugarVacunacion.getText().trim();

        // Validar que al menos el nombre y el DPI estén presentes
        if (nombre.isEmpty() || dpi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre y el DPI son campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Agregar una fila a la tabla
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();
        model.addRow(new Object[]{nombre, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion});

        // Limpiar los JTextField
        LimpiarTextField();

        // Actualizar el contador de registros
        countAndDisplayRecords();


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        LimpiarTextField();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        // Verificar si hay una fila seleccionada
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();

        // Eliminar la fila seleccionada
        model.removeRow(selectedRowIndex);

        // Limpiar los JTextField
        LimpiarTextField();

        // Reiniciar el índice de la fila seleccionada
        selectedRowIndex = -1;

        // Actualizar el contador de registros
        countAndDisplayRecords();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed

        // Obtener la ruta de archivo deseada para guardar los datos encriptados
        String rutaArchivo = obtenerRutaArchivo();

        // Verificar si se seleccionó una ruta de archivo válida
        if (rutaArchivo != null) {
            // Agregar la extensión .txt si no está presente
            if (!rutaArchivo.toLowerCase().endsWith(".txt")) {
                rutaArchivo += ".txt";
            }

            // Obtener la clave de encriptación del usuario (puedes cambiar esto según tus necesidades)
            String clave = JOptionPane.showInputDialog(this, "Ingrese la clave de encriptación:", "Clave de Encriptación", JOptionPane.PLAIN_MESSAGE);

            // Verificar si se ingresó una clave
            if (clave != null && !clave.isEmpty()) {
                // Llamar al método para encriptar y guardar los datos de la tabla
                EncriptadorTabla.encriptarYGuardarTabla(tblBinario, rutaArchivo, clave);
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese una clave de encriptación válida.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEncriptarActionPerformed

    private void btnDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencriptarActionPerformed

        // Obtener la ruta de archivo deseada para desencriptar los datos
        String rutaArchivo = obtenerRutaArchivo();

        // Verificar si se seleccionó una ruta de archivo válida
        if (rutaArchivo != null) {
            // Obtener la clave de desencriptación del usuario
            String clave = obtenerClave("Ingrese la clave de desencriptación:");

            // Verificar si se ingresó una clave válida
            if (clave != null && !clave.isEmpty()) {
                // Desencriptar y mostrar los datos en la tabla
                desencriptarYMostrarTabla(tblBinario, rutaArchivo, clave);
            } else {
                mostrarMensajeError("Por favor, ingrese una clave de desencriptación válida.");
            }
        }

    }
// Método para obtener la clave del usuario

    private String obtenerClave(String mensaje) {
        return JOptionPane.showInputDialog(this, mensaje, "Clave de Desencriptación", JOptionPane.PLAIN_MESSAGE);
    }

// Método para mostrar mensajes de error
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
// Método para desencriptar los datos de un archivo y mostrarlos en una tabla

    private void desencriptarYMostrarTabla(JTable tabla, String rutaArchivo, String clave) {
        try (BufferedReader reader = new BufferedReader(new FileReader(rutaArchivo))) {
            // Leer la primera línea del archivo para determinar el número de columnas
            String primeraLinea = reader.readLine();
            List<String> columnas = List.of(primeraLinea.split(";"));

            // Leer el resto de las líneas para obtener los datos
            List<List<String>> datosDesencriptados = reader.lines()
                    .map(linea -> List.of(linea.split(";")).stream()
                    .map(datoEncriptado -> desencriptarVigenere(datoEncriptado, clave))
                    .collect(Collectors.toList()))
                    .collect(Collectors.toList());

            // Crear el modelo de tabla y agregar las columnas
            DefaultTableModel model = new DefaultTableModel(columnas.toArray(), 0);

            // Agregar las filas al modelo de la tabla
            datosDesencriptados.forEach(fila -> model.addRow(fila.toArray()));

            // Asignar el modelo de tabla creado a la tabla proporcionada
            tabla.setModel(model);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al leer el archivo encriptado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// Método para desencriptar un texto utilizando el cifrado Vigenère
    private String desencriptarVigenere(String textoEncriptado, String clave) {
        StringBuilder textoDesencriptado = new StringBuilder();

        // Repetir la clave hasta que tenga la misma longitud que el texto encriptado
        while (clave.length() < textoEncriptado.length()) {
            clave += clave;
        }

        // Recorrer cada carácter del texto encriptado
        for (int i = 0; i < textoEncriptado.length(); i++) {
            char caracter = textoEncriptado.charAt(i);
            // Obtener el desplazamiento para este carácter según la clave
            int desplazamiento = clave.charAt(i) - 'A';
            // Restar el desplazamiento al carácter para deshacer la encriptación y agregarlo al texto desencriptado
            textoDesencriptado.append((char) ((caracter - desplazamiento + 256) % 256));
        }

        return textoDesencriptado.toString();
    }//GEN-LAST:event_btnDesencriptarActionPerformed

    private void btnGuardarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTablaActionPerformed

        // Verifica que la tabla no sea nula
        if (tblBinario == null) {
            JOptionPane.showMessageDialog(null, "La tabla tblBinario no está inicializada.");
            return;
        }

        // Obtiene el modelo de la tabla
        TableModel model = tblBinario.getModel();

        // Verifica que el modelo de la tabla no sea nulo
        if (model == null) {
            JOptionPane.showMessageDialog(null, "El modelo de la tabla tblBinario no está inicializado.");
            return;
        }

        // Elige la ubicación y el nombre del archivo donde se guardará la tabla
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file + ".txt"))) {
                // Escribe los nombres de las columnas
                for (int i = 0; i < model.getColumnCount(); i++) {
                    bw.write(model.getColumnName(i) + (i == model.getColumnCount() - 1 ? "" : ","));
                }
                bw.write("\n");

                // Itera sobre las filas
                for (int i = 0; i < model.getRowCount(); i++) {
                    // Itera sobre las columnas
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object value = model.getValueAt(i, j);
                        bw.write((value != null ? value.toString() : "") + (j == model.getColumnCount() - 1 ? "" : ","));
                    }
                    bw.write("\n");
                }
                JOptionPane.showMessageDialog(null, "Tabla guardada correctamente.");
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar la tabla.");
            }
        }

    }//GEN-LAST:event_btnGuardarTablaActionPerformed

    private void btnGenerarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarArbolActionPerformed
        // Crear un objeto BinaryTree
        BinaryTree binaryTree = new BinaryTree();

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tblBinario.getModel();

        // Insertar los datos de la tabla en el árbol binario
        for (int i = 0; i < model.getRowCount(); i++) {
            String name = (String) model.getValueAt(i, 0);
            String dpi = (String) model.getValueAt(i, 1);
            String departamento = (String) model.getValueAt(i, 2);
            String municipio = (String) model.getValueAt(i, 3);
            String fechaPrimera = (String) model.getValueAt(i, 4);
            String fechaSegunda = (String) model.getValueAt(i, 5);
            String fechaTercera = (String) model.getValueAt(i, 6);
            String lugarVacunacion = (String) model.getValueAt(i, 7);
            binaryTree.insert(name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
        }

        // Crear el modelo para el árbol visual
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
        createTree(binaryTree.getRoot(), root);
        JTree tree = new JTree(root);

        // Mostrar el árbol en un nuevo JFrame
        JFrame frame = new JFrame("Árbol Binario");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(new JScrollPane(tree));
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnGenerarArbolActionPerformed

// Método para crear el árbol visual
    private void createTree(Node node, DefaultMutableTreeNode treeNode) {
        if (node != null) {
            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(node.name + " (" + node.dpi + ")");
            treeNode.add(newNode);
            createTree(node.left, newNode);
            createTree(node.right, newNode);
        }
    }

    /* 
    // Método para permitir al usuario elegir la ruta del archivo encriptado a desencriptar
    private String obtenerRutaArchivoEncriptado() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar Archivo Encriptado");
        // Filtrar solo archivos .txt (o el formato en que se guardaron los datos encriptados)
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Texto", "txt");
        fileChooser.setFileFilter(filter);

        // Mostrar el cuadro de diálogo para seleccionar el archivo encriptado
        int seleccion = fileChooser.showOpenDialog(this);

        // Verificar si se seleccionó un archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener la ruta del archivo seleccionado por el usuario
            File archivoSeleccionado = fileChooser.getSelectedFile();
            return archivoSeleccionado.getAbsolutePath();
        } else {
            return null; // El usuario canceló la operación
        }
    }

  private void desencriptarYMostrarTabla(String rutaArchivoEncriptado, String clave) {
        try {
            // Crear el lector para el archivo encriptado
            BufferedReader reader = new BufferedReader(new FileReader(rutaArchivoEncriptado));

            // Crear el modelo de tabla para mostrar los datos desencriptados
            DefaultTableModel model = new DefaultTableModel();

            // Leer cada línea del archivo encriptado
            String linea;
            while ((linea = reader.readLine()) != null) {
                // Dividir la línea en datos encriptados separados por el separador utilizado al encriptar (por ejemplo, ';')
                String[] datosEncriptados = linea.split(";");

                // Crear un array para almacenar los datos desencriptados
                String[] datosDesencriptados = new String[datosEncriptados.length];

                // Desencriptar cada dato encriptado utilizando la clave proporcionada
                for (int i = 0; i < datosEncriptados.length; i++) {
                    datosDesencriptados[i] = desencriptarVigenere(datosEncriptados[i], clave);

                    // Imprimir los datos desencriptados en la consola para verificar
                    System.out.println("Dato desencriptado: " + datosDesencriptados[i]);
                }

                // Agregar la fila con los datos desencriptados al modelo de tabla
                model.addRow(datosDesencriptados);
            }

            // Asignar el modelo de tabla desencriptado a la tabla tblBinario
            tblBinario.setModel(model);

            // Cerrar el lector
            reader.close();

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Datos desencriptados y mostrados en la tabla exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al desencriptar y mostrar los datos en la tabla.", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }*/
// Método para permitir al usuario elegir la ruta de archivo donde guardar los datos encriptados
    private String obtenerRutaArchivo() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Datos Encriptados");

        // Mostrar el cuadro de diálogo para seleccionar la ruta de archivo
        int seleccion = fileChooser.showSaveDialog(this);

        // Verificar si se seleccionó una ruta de archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener la ruta de archivo seleccionada por el usuario
            File archivoSeleccionado = fileChooser.getSelectedFile();
            return archivoSeleccionado.getAbsolutePath();
        } else {
            return null; // El usuario canceló la operación
        }
    }

    public void LimpiarTextField() {
        // Limpiar los JTextField
        txtNombre.setText("");
        txtDpi.setText("");
        txtDepartamento.setText("");
        txtMunicipio.setText("");
        txtFechaPrimera.setText("");
        txtFechaSegunda.setText("");
        txtFechaTercera.setText("");
        txtLugarVacunacion.setText("");

    }
// Clase Node para representar los nodos del árbol

    public class BinaryTree {

        private Node root;

        public BinaryTree() {
            root = null;
        }

        public Node getRoot() {
            return root;
        }

        public void insert(String name, String dpi, String departamento, String municipio, String fechaPrimera, String fechaSegunda, String fechaTercera, String lugarVacunacion) {
            root = insertRec(root, name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
        }

        private Node insertRec(Node root, String name, String dpi, String departamento, String municipio, String fechaPrimera, String fechaSegunda, String fechaTercera, String lugarVacunacion) {
            if (root == null) {
                root = new Node(name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
                return root;
            }
            if (dpi.compareTo(root.dpi) < 0) {
                root.left = insertRec(root.left, name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
            } else if (dpi.compareTo(root.dpi) > 0) {
                root.right = insertRec(root.right, name, dpi, departamento, municipio, fechaPrimera, fechaSegunda, fechaTercera, lugarVacunacion);
            }
            return root;
        }

        public void inorden(Node node, DefaultTableModel model) {
            if (node != null) {
                inorden(node.left, model);
                model.addRow(new Object[]{node.name, node.dpi, node.departamento, node.municipio, node.fechaPrimera, node.fechaSegunda, node.fechaTercera, node.lugarVacunacion});
                inorden(node.right, model);
            }
        }

        public void preorden(Node node, DefaultTableModel model) {
            if (node != null) {
                model.addRow(new Object[]{node.name, node.dpi, node.departamento, node.municipio, node.fechaPrimera, node.fechaSegunda, node.fechaTercera, node.lugarVacunacion});
                preorden(node.left, model);
                preorden(node.right, model);
            }
        }

        public void postorden(Node node, DefaultTableModel model) {
            if (node != null) {
                postorden(node.left, model);
                postorden(node.right, model);
                model.addRow(new Object[]{node.name, node.dpi, node.departamento, node.municipio, node.fechaPrimera, node.fechaSegunda, node.fechaTercera, node.lugarVacunacion});
            }
        }

    }

    public class Node {

        String name;
        String dpi;
        String departamento;
        String municipio;
        String fechaPrimera;
        String fechaSegunda;
        String fechaTercera;
        String lugarVacunacion;
        Node left;
        Node right;

        public Node(String name, String dpi, String departamento, String municipio, String fechaPrimera, String fechaSegunda, String fechaTercera, String lugarVacunacion) {
            this.name = name;
            this.dpi = dpi;
            this.departamento = departamento;
            this.municipio = municipio;
            this.fechaPrimera = fechaPrimera;
            this.fechaSegunda = fechaSegunda;
            this.fechaTercera = fechaTercera;
            this.lugarVacunacion = lugarVacunacion;
            this.left = null;
            this.right = null;
        }
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccionesBusquedaInsercion;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JButton btnBorrarCargar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDesencriptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JButton btnGenerarArbol;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarTabla;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnPostOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBinario;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtContador;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtFechaPrimera;
    private javax.swing.JTextField txtFechaSegunda;
    private javax.swing.JTextField txtFechaTercera;
    private javax.swing.JTextField txtLugarVacunacion;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
